config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :game_matches do
    get 'visualisation'
  end
  resources :teams  do
    get 'visualisation'
  end

  root 'landing_pages#index' #change this to be the landing page

end

app/models/landing_page.rb
class LandingPage < ActiveRecord::Base
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  before_action :set_landing_page, only: [:show, :edit, :update, :destroy]

  # GET /landing_pages
  # GET /landing_pages.json
  def index
    @landing_pages = LandingPage.all
  end

  # GET /landing_pages/1
  # GET /landing_pages/1.json
  def show
  end

  # GET /landing_pages/new
  def new
    @landing_page = LandingPage.new
  end

  # GET /landing_pages/1/edit
  def edit
  end

  # POST /landing_pages
  # POST /landing_pages.json
  def create
    @landing_page = LandingPage.new(landing_page_params)

    respond_to do |format|
      if @landing_page.save
        format.html { redirect_to @landing_page, notice: 'Landing page was successfully created.' }
        format.json { render :show, status: :created, location: @landing_page }
      else
        format.html { render :new }
        format.json { render json: @landing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landing_pages/1
  # PATCH/PUT /landing_pages/1.json
  def update
    respond_to do |format|
      if @landing_page.update(landing_page_params)
        format.html { redirect_to @landing_page, notice: 'Landing page was successfully updated.' }
        format.json { render :show, status: :ok, location: @landing_page }
      else
        format.html { render :edit }
        format.json { render json: @landing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landing_pages/1
  # DELETE /landing_pages/1.json
  def destroy
    @landing_page.destroy
    respond_to do |format|
      format.html { redirect_to landing_pages_url, notice: 'Landing page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landing_page
      @landing_page = LandingPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landing_page_params
      params[:landing_page]
    end
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/_form.html.erb
<%= form_for(@landing_page) do |f| %>
  <% if @landing_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landing_page.errors.count, "error") %> prohibited this landing_page from being saved:</h2>

      <ul>
      <% @landing_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/landing_pages/edit.html.erb
<h1>Editing Landing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @landing_page %> |
<%= link_to 'Back', landing_pages_path %>

app/views/landing_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landing Page</h1>

app/views/landing_pages/new.html.erb
<h1>New Landing Page</h1>

<%= render 'form' %>

<%= link_to 'Back', landing_pages_path %>

app/views/landing_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_landing_page_path(@landing_page) %> |
<%= link_to 'Back', landing_pages_path %>