config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :game_matches do
    get 'visualisation'
  end
  resources :teams  do
    get 'visualisation'
  end

  root 'landing_pages#index' #change this to be the landing page

end

app/models/game_match.rb
class GameMatch < ActiveRecord::Base
  require 'csv'

  has_and_belongs_to_many :teams

  def self.link_games_teams
    GameMatch.each do |game|
      game.teams
    end
  end

  def self.import
    create_record(2008,'2008-Table1.csv')
    create_record(2009,'2009-Table1.csv')
    create_record(2010,'2010-Table1.csv')
    create_record(2011,'2011-Table1.csv')
    create_record(2012,'2012-Table1.csv')
    create_record(2013,'2013-Table1.csv')
  end

  def self.create_record (year, file)
    CSV.foreach(file, headers: true) do |row|
      next if row["Date"].starts_with?("BYES")
      csv_time = row["Time"].nil? ? "" : row["Time"]
      csv_date = row["Date"]

      date = DateTime.parse(csv_date + " " + csv_time)
      GameMatch.create(
        year: year,
        round: row["Round"],
        date: date,
        home_team: row["Home Team"],
        away_team: row["Away Team"],
        home_score: row["Score"].nil? ? nil : row["Score"].split('–')[0],
        away_score: row["Score"].nil? ? nil : row["Score"].split('–')[1],
        venue: row["Venue"]
      )
    end
  end
end

app/controllers/game_matches_controller.rb
class GameMatchesController < ApplicationController
  before_action :set_game_match, only: [:show, :edit, :update, :destroy]

  # GET /game_matches
  # GET /game_matches.json
  def index
    @game_matches = GameMatch.all
    # GameMatch.import
  end

  # GET /game_matches/1
  # GET /game_matches/1.json
  def show
  end

  # GET /game_matches/new
  def new
    @game_match = GameMatch.new
  end

  # GET /game_matches/1/edit
  def edit
  end

  # POST /game_matches
  # POST /game_matches.json
  def create
    @game_match = GameMatch.new(game_match_params)

    respond_to do |format|
      if @game_match.save
        format.html { redirect_to @game_match, notice: 'Game match was successfully created.' }
        format.json { render :show, status: :created, location: @game_match }
      else
        format.html { render :new }
        format.json { render json: @game_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_matches/1
  # PATCH/PUT /game_matches/1.json
  def update
    respond_to do |format|
      if @game_match.update(game_match_params)
        format.html { redirect_to @game_match, notice: 'Game match was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_match }
      else
        format.html { render :edit }
        format.json { render json: @game_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_matches/1
  # DELETE /game_matches/1.json
  def destroy
    @game_match.destroy
    respond_to do |format|
      format.html { redirect_to game_matches_url, notice: 'Game match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def visualisation
    @team_labels = []
    Team.all.each do |team|
      @team_labels << team.name
    end
    @game_match_data = {
      labels: @team_labels,
      year_2008: generate_data(2008),
      year_2009: generate_data(2009),
      year_2011: generate_data(2011),
      year_2012: generate_data(2012),
      year_2013: generate_data(2013)
    }
  end

  def generate_data(year)
    team_matrix = Array.new(@team_labels.count) { Array.new(@team_labels.count, 0)}
    GameMatch.where(year: year).all.each do |match|
      home_team_index = @team_labels.find_index(match.home_team)
      away_team_index = @team_labels.find_index(match.away_team)
      team_matrix[home_team_index][away_team_index] += match.home_score
      team_matrix[away_team_index][home_team_index] += match.away_score
    end
    team_matrix
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_match
      @game_match = GameMatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_match_params
      params.require(:game_match).permit(:year, :round, :date, :home_team, :away_team, :home_score, :away_score, :venue)
    end
end

app/helpers/game_matches_helper.rb
module GameMatchesHelper
end

app/views/game_matches/_form.html.erb
<%= form_for(@game_match) do |f| %>
  <% if @game_match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_match.errors.count, "error") %> prohibited this game_match from being saved:</h2>

      <ul>
      <% @game_match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :round %><br>
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :home_team %><br>
    <%= f.text_field :home_team %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br>
    <%= f.text_field :away_team %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br>
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br>
    <%= f.number_field :away_score %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_matches/edit.html.erb
<h1>Editing Game Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_match %> |
<%= link_to 'Back', game_matches_path %>

app/views/game_matches/index.html.erb
<p id="notice"><%= notice %></p>
<%= flash[:notice] %>

<h1>Listing Game Matches</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Round</th>
      <th>Date</th>
      <th>Home team</th>
      <th>Away team</th>
      <th>Home score</th>
      <th>Away score</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_matches.each do |game_match| %>
      <tr>
        <td><%= game_match.year %></td>
        <td><%= game_match.round %></td>
        <td><%= game_match.date %></td>
        <td><%= game_match.home_team %></td>
        <td><%= game_match.away_team %></td>
        <td><%= game_match.home_score %></td>
        <td><%= game_match.away_score %></td>
        <td><%= game_match.venue %></td>
        <td><%= link_to 'Show', game_match %></td>
        <td><%= link_to 'Edit', edit_game_match_path(game_match) %></td>
        <td><%= link_to 'Destroy', game_match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game match', new_game_match_path %>

app/views/game_matches/new.html.erb
<h1>New Game Match</h1>

<%= render 'form' %>

<%= link_to 'Back', game_matches_path %>

app/views/game_matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @game_match.year %>
</p>

<p>
  <strong>Round:</strong>
  <%= @game_match.round %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game_match.date %>
</p>

<p>
  <strong>Home team:</strong>
  <%= @game_match.home_team %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game_match.away_team %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @game_match.home_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @game_match.away_score %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @game_match.venue %>
</p>

<%= link_to 'Edit', edit_game_match_path(@game_match) %> |
<%= link_to 'Back', game_matches_path %>

app/views/game_matches/visualisation.html.erb
<h1 id="game_visualisation" data="<%= @game_match_data.to_json %>">Game Matches</h1>

<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://mbostock.github.com/d3/d3.js?1.29.1"></script>
<div id='match_chord_diagram'></div>

<script type="text/javascript">
  var data = JSON.parse($('#game_visualisation').attr('data'));

  var width = 1100,
  height = 1100,
  outerRadius = 370,
  innerRadius = outerRadius - 30,
  r1 = outerRadius + 30,
  r0 = r1 - 80;

  var color = d3.scale.category20();

  var formatPercent = d3.format(".1%");

  var tooltip = d3.select("body")
    .append("div")
    .style("width", "200px")
    .style("height", "50px")
    .style("text-align", "center")
    .style("background", "lightblue")
    .style("padding", "2px")
    .style("font", "12px sans-serif")
    .style("border", "0px")
    .style("border-radius", "8px")
    .style("position", "absolute")
    .style("z-index", "10")
    .style("visibility", "hidden");

  var arc = d3.svg.arc()
    .innerRadius(innerRadius)
    .outerRadius(outerRadius);

  var layout = d3.layout.chord()
      .padding(0.04)
      .sortSubgroups(d3.ascending)
      .sortChords(d3.descending);

  var path = d3.svg.chord()
    .radius(innerRadius);

  var svg = d3.select("#match_chord_diagram").append("svg")
    .attr("width", width)
    .attr("height", height)
    .append("g")
    .attr("id", "circle")
    .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

  svg.append("circle")
    .attr("r", outerRadius);

  layout.matrix(data.year_2008);


  var group = svg.selectAll(".group")
    .data(layout.groups)
    .enter().append("g")
    .on("mouseover", fade(.02))
    .on("mouseout", fade(.80));

  var groupPath = group.append("path")
    .attr("id", function(d,i) {return "group" + i; })
    .attr("d", arc)
    .style("fill", function(d) { return color(d.index); });

  var groupText = group.append("text")
    .each(function(d) { d.angle = (d.startAngle + d.endAngle) / 2; })
    .attr("dy", ".35em")
    .attr("text-anchor", function(d) { return d.angle > Math.PI ? "end" : null; })
      .attr("transform", function(d) {
        return "rotate(" + (d.angle * 180 / Math.PI - 90) + ")"
            + "translate(" + (r0 + 55) + ")"
            + (d.angle > Math.PI ? "rotate(180)" : "");
      })
    .text(function(d, i) {
      return data.labels[i];
    });

  var chord = svg.selectAll(".chord")
    .data(layout.chords)
    .enter().append("path")
    .attr("class", "chord")
    .style("fill", function(d) { return color(d.source.index); })
    .style("stroke", "grey")
    .attr("d", d3.svg.chord().radius(innerRadius))
    .on("mouseover", function(d){return tooltip.style("visibility", "visible").text(data.labels[d.source.index] + ": "+ d.source.value + " VS " + data.labels[d.target.index] + ": "+ d.target.value);})
    .on("mousemove", function(d){return tooltip.style("top", (event.pageY-10)+"px").style("left",(event.pageX+10)+"px").text(data.labels[d.source.index] + ": "+ d.source.value + " VS " + data.labels[d.target.index] + ": "+ d.target.value);})
    .on("mouseout", function(){return tooltip.style("visibility", "hidden");});

  function fade(opacity) {
    return function(d, i) {
      svg.selectAll(".chord")
          .filter(function(d) { return d.source.index != i && d.target.index != i; })
        .transition()
          .style("stroke-opacity", opacity)
          .style("fill-opacity", opacity)
    };
  }

</script>